/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardStudentRouteImport } from './routes/dashboard/student'
import { Route as DashboardGrowerRouteImport } from './routes/dashboard/grower'
import { Route as DashboardCoordinatorRouteImport } from './routes/dashboard/coordinator'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGrowerRoute = DashboardGrowerRouteImport.update({
  id: '/grower',
  path: '/grower',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoordinatorRoute = DashboardCoordinatorRouteImport.update({
  id: '/coordinator',
  path: '/coordinator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/coordinator': typeof DashboardCoordinatorRoute
  '/dashboard/grower': typeof DashboardGrowerRoute
  '/dashboard/student': typeof DashboardStudentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/coordinator': typeof DashboardCoordinatorRoute
  '/dashboard/grower': typeof DashboardGrowerRoute
  '/dashboard/student': typeof DashboardStudentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/coordinator': typeof DashboardCoordinatorRoute
  '/dashboard/grower': typeof DashboardGrowerRoute
  '/dashboard/student': typeof DashboardStudentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/coordinator'
    | '/dashboard/grower'
    | '/dashboard/student'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/coordinator'
    | '/dashboard/grower'
    | '/dashboard/student'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/dashboard/admin'
    | '/dashboard/coordinator'
    | '/dashboard/grower'
    | '/dashboard/student'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/grower': {
      id: '/dashboard/grower'
      path: '/grower'
      fullPath: '/dashboard/grower'
      preLoaderRoute: typeof DashboardGrowerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/coordinator': {
      id: '/dashboard/coordinator'
      path: '/coordinator'
      fullPath: '/dashboard/coordinator'
      preLoaderRoute: typeof DashboardCoordinatorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardCoordinatorRoute: typeof DashboardCoordinatorRoute
  DashboardGrowerRoute: typeof DashboardGrowerRoute
  DashboardStudentRoute: typeof DashboardStudentRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardCoordinatorRoute: DashboardCoordinatorRoute,
  DashboardGrowerRoute: DashboardGrowerRoute,
  DashboardStudentRoute: DashboardStudentRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
